### ISSUE TITLE
A2 make issue

### ISSUE THREAD

**Issue by WyattLiu** [dilevin/computer-graphics-csc418#1]
Hi,

We don't have issue button in A2 so please allow me to put it here.

The issue is that we cannot compile without the shared dir and I managed to pull that off using the original repo back in months ago.

It can compile in this fashion. Just added a shared/ please consider fix for the class
https://github.com/WyattLiu/CSC418FixA2/tree/master/computer-graphics-ray-casting

**Comment by ACalza** [comment]
Does your project make? I spent a couple of hours reading up on cmake since Eigen it had issues being built. I finally got around to build, but now it doesn't make.

**Comment by dilevin** [comment]
Please use the exact git command on the A2 repo. This will checkout a branch of the project with the shared directory

**Comment by dilevin** [comment]
Here’s the command:

git clone --recursive -b fix https://github.com/dilevin/computer-graphics-ray-casting.git

The A2 issues page is open now please move all comments about this there. We won’t respond to this issues about A2 posted in the main issues thread any more.
