### ISSUE TITLE
Clarifying the set of key-frame poses in Lecture 7 of Slides

### ISSUE THREAD

**Issue by Sheepf75** [dilevin/computer-graphics-csc418#19]
Hi,

In lecture 7 of the slides it mentions how we can specify key-frame poses with a set of Euler angles:
![image](https://user-images.githubusercontent.com/60700618/76147960-92dfd380-606f-11ea-89e2-0ba1e41c9085.png)

However, I was confused by the first three entries of Theta where 

<img src="https://render.githubusercontent.com/render/math?math=\Theta_1=\Theta_{1, 1}, \Theta_2=\Theta_{1, 1}"> and <img src="https://render.githubusercontent.com/render/math?math=\Theta_3=\Theta_{1, 1}">

Does <img src="https://render.githubusercontent.com/render/math?math=\Theta_{i, j}"> represent the angle in axis j at time frame T = i? If so, should the first three entries be:

<img src="https://render.githubusercontent.com/render/math?math=\Theta_1 = \Theta_{1, 1}, \Theta_2 = \Theta_{1, 2}, \Theta_3 = \Theta_{1, 3}">

Thanks!

**Comment by darren-moore** [comment]
The first 3 entries should be `(theta_11, theta_12, theta_13...`, where `theta_ij` represents the j'th angle of the i'th bone. On this slide, `theta` specifies exactly _one pose_ at some time. Later slides use `theta_t` for parametric `t \in [0,1]` to denote poses over time.

**Comment by Sheepf75** [comment]
Oh I see, thank you so much!

**Comment by dilevin** [comment]
For next time please ask assignment specific questions on the assignment GitHub pages.
