### ISSUE TITLE
Incorrect Equations in Lecture 2 Slides

### ISSUE THREAD

**Issue by auderian** [dilevin/computer-graphics-csc418#4]
I believe the Lecture 2 slides make a mistake when presenting the equations for computing an intersection with a triangle. They state, beginning on slide 52, that:
`p1 =  α ⋅ t1 + β ⋅ t2`
I believe that the formula for a point on the triangle should instead be:
`p1 =  a + α ⋅ t1 + β ⋅ t2`
Where t1 and t2 are the vector edges of the triangle, a is the corner that is the starting point of the triangle, and p1 is the point on the triangle.

**Comment by dilevin** [comment]
You are right that you should have an offset.

I think I said this during lecture (but it’s not on the slides) that I’m assuming the corner of the triangle is at the origin of the coordinate system in the slides.
